name: Fearless Alexa Skill CI/CD
on: [push]

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - run: |
  #         cd lambda;
  #         npm install;
  #         npm run test;
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    if: ${{ true }}
    steps:
      - name: Checkout and deploy to dev
        uses: actions/checkout@v2
      - run: |
          sudo npm install -g ask-cli;
          cd lambda;
          npm install;
      - run: ask deploy --ignore-hash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ASK_ACCESS_TOKEN: ${{ secrets.ASK_ACCESS_TOKEN }}
          ASK_REFRESH_TOKEN: ${{ secrets.ASK_REFRESH_TOKEN }}
          ASK_VENDOR_ID: ${{ secrets.ASK_VENDOR_ID }}
          SKILL_ID: ${{ secrets.SKILL_ID }}
